CREATE TABLE `products` (
	`id` text PRIMARY KEY NOT NULL,
	`agentId` text,
	`sku` text,
	`name` text,
	`description` text,
	`priceValue` text,
	`priceCurrency` text,
	`priceInclTaxValue` text,
	`priceInclTaxCurrency` text,
	`taxRate` real,
	`taxValue` real,
	`width` real,
	`height` real,
	`length` real,
	`weight` real,
	`widthUnit` text,
	`heightUnit` text,
	`lengthUnit` text,
	`weightUnit` text,
	`brand` text,
	`status` text,
	`imageUrl` text,
	`attributes` text,
	`variants` text,
	`images` text,
	`tags` text,
	`createdAt` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updatedAt` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
